language: node_js
node_js:
- stable
notifications:
  slack:
    secure: ZLGzk4OjvQlEOzmlxzloHfwYyPnjURGjJwgTHpL5fCdayOPSmOZLKo/HLrFNasN8OR6ykuC9ZIsZxXYaFkMUr8K9X9z4MxeneLjsiAXn60PP9EFMn+E7gtwkzljsz+yXw9CnPeuJmoH5NMLwixSHNr5E1MRsEVOHFmnx8cIrlOsBWIvHPXegW7AhLAuM7WwGZNTJDAyCbIZF/h1djfj7qB6lcsijSfEpi16nYrNqlNe9W1MqUUFZ29jstvMBXkukSqnwKPXCSpPVUT4/Ca/f5867vmPARv/5h+MD72EZSarscoduldNYLmeV72RR+ZMrECh2mlt1kQfNAjmqobwSWznpARjABT3WbEgdNIA6vFTD8oxdOFV7CxkU+0j6wWEn1uacAaN/t8/oqTH5zj2GL3qigY2NCNSOulDfJJillWg92+rn9zdASQL7pZUFrGvO5JC4+XG4ULOvtjiF5U0ebQ9fWquSXiBcMXeD7C6QcT2/gc6CLiZZjFbkfHSgH4EKHPo6nhu8akfxGy1LxvJKc3TocUCBf6fHX1hvdAa40uGNzO7sRVfedtL+01eGKLeoXs6yW9QKK1iTdiBq68EhyQPmPN5s8nF31n3uj+hayyLRmsHzbUIQwdZALdbGUabHZ7wNoPNheTs94up7ttgZAWOlXm/NrgHAxLQrKDLS/ic=
script:
- npm run build
