language: node_js
node_js:
- stable
notifications:
  slack:
    secure: djjYszjkBe0Qv49V3udfsADVQwS6xugUxhjXPofmlQbYN+NoAcmYQgFjJ6wiGqdUqc6qEMPn/ycKeGUUr1vLQFX04JrSBvzdnHwD7I+QiARlmn1SJ8nT4Hc3rl7hR3IJ8jGuRzGD80+KaoZCbrGRQIdSdBlpxqPxHzkN4Igm7s16b83p0tsVf6XY81/DGOTCVzMGZZPmfZk0D4xANrE23Sabm9H9wiV8zlvWRz44DMMPOPs19Kd3cB4wftXLZbW5KCuRgEa6Q9Ltix4DrbNSqAbNFQ0lfKBQIRkRGyhO1tdoW27oa1+WsmNM9hEQEp+EI79chn1B0dHBdcjCGqL3K2EcxMoWUplKTIaPHon7lPULcZBhv/pm5KJLqa4I5NcQ85j4aCJMmNcdFDlDCBz1G6V/++OF+DSFaBrDPMGPEkXpAojvH4Nt4lLF2ZLAgML5vZOA5vucMNImnym+zh6qw9G54e2/zfXGJyg4DwxR2vtmuKhPbhScqzzAShz6TByIEESZotAgJwc4qntNacQHzLlcROaS5xx+M2Zn+i6xqJpAEcnt56ZY6jYzIXwMHSAxeSy8C64TQpzFhb9XrcnowZtbnOeGP1Rk9714gcsJNCeo10R+jI9VbdAOjAhtq6jZHc2+vYkZOSSUNhsJB0zORBByO23/VkxTvdhItZgMA9o=
script:
- npm run build
