language: node_js
node_js:
- stable
notifications:
  slack:
    secure: au/uyG744gj+u1Wqr3VF5DYP0GqX4xWitTUFVQezmTJmEZN0Et+M3eUuLvWp1xiIpH45sM2FkGa8rUXLoxQ72gfiKb/KOi1OSv7zFb8MjQd4RcCjnHJ/gma+oqsynyR5cCcO1mAl44PKLCyJEUnNnokKv8WJrL6mgEQ46FyMhujJc2dedqbkbCJZPWLcnetJhFoNtoV7j9j7nayXg1m4I6XVs5pe8i1Jz8y9gw2JzscZLh5ow/4JMCa/lOUQtHubSvnDA41UzHEY2ht7HkPZ2zrPas1fdyJ92SpZMvuIcFEv+FH6I+UvH/O1KEWHLE4eGNuYPXmq2wQCLvP5Ll7pzOBt93eLpaQZWrwBp1OjmIc9L7ytQmBkKgC4LNp1jZGgITO5Cb3ncp5jCbFRRcQ2NeFiaoTF/BSH2ArZ0J4l6ytFY1eHGFGc6H2YNwxFkQbGy64wKQgiUp5qQ88t3terRPHzcz0Aa5CVRM0Zc/f2bOu8M7S+RBI4NgJNNU97mVnHSWHnnTY2hrP5P6v2mOtxWGbG3aaNi9ldvRTPGCOnW+vsEHOYdDLvZDjlq9u3BmIS0Xjoq+3T5BBYjM8enXKXiorM8IoXa8oPjAdKaufPpErG81dO8/NyYW/1Xwif7KmegBMXlX9yrQ6LUCEPGqqIMWk/E3R9Z6yZ1+xUJ+MQfyo=
script:
- npm run build
