language: node_js
node_js: -"stable"
notifications:
  slack:
    rooms:
      secure: zGoDwb07OIiVi/nSra/oGfe3tuf3W5dMSJOp4c4yGXq4sVcxhT8qLH18AEkYfLdYa5fsb+z+Kj2ary3N68mokg4/rzwI5ZKtVPCxvB3MppXz7JUnwQxKetOOhuqkZKmyE3m8iiJmoxqHVwEp4NSNAl69EZ7Woi+xoD9Unh1QZci8hN85xAO361sjw14Xs4qzVg/6Yqg4pCfal9zYVdHZp/Fo5jgC8hAzjyN5n83q+uQs0+h1HPlbb5UzCvjfRfnqbKF1/Ssg/0HvpxF0chSTFkL4kKdOkc8IG10eaEsW+MTmSFz1zWJjQuvxVqT+ny5xvuwdLUsUwi9gvWtMg4mSzzt4ohd2YKXDX/4NwcSbtVKO15hbGlqh9LI3bNV7V+WgbzjZ+J0xPBCqWDOjGIW8JRjGq1/VSInyWPLPV2kKm784pLZuERxiArSphL8klBT2aZzc6WaDqdIPdVgj0qKhHQGQeW8I/nT3hnGDyVgSbvh+ppHZ7q2yy8i/4741CopWbmrpTT7tEEP1yyZSetiUV7HzfFnkJ+iQE9S4lHvpJtyxlr7FjBEx78HE5Xj+57N/ltwS9+ptPKBEmriTxjlqqYzs9fq93QRleE9Sh3LAFetHlcps3wxu5Le2Q03Xndt17BL7yszU4yaAlb0YCbZPEN8cYKUpiZf6NbL0CBxRktw=
script:
- npm run build
