language: node_js
node_js:
- stable
notifications:
  slack:
    secure: xuTijYqM5+MYs+uAbSIekeN9AEprDXBdH3VEutfaNsUNLXBla0ypD8S4Sk5Ooj4yTFWzugFLMp2OUBEzU6NBFwHx4Uuut1NJH0bL6FAGBEXZXyB2fzzupcnpwgTRra1+LCKAlajsGQUv18J8A4xtKXVpoH4TdCKGO4341grUvvheAgUPZENrzvxB1ZUsdTB6CUd9VxcyPuYo1qUZ5d4Y2T9hHUMDsZLBO0e4eQKLCaIGQB5sa2UK8L5ctZfPfa/wTWDvi4pmlpU8B0iD5KLsqMZ+IYjn4utZQoIWTpMdD9FYpmHAPZ2FBgA18bVPIJpFXl8hAf3iVi4f3xJ/SZ719GHPaVYmBXUHPSCMyozvr7RaCA+m/EHrrSafJbROwKbOCGIRPT80DQvHH5FMJzkRNERgVd6vOvgOImBWB2VbyuzVR1oLurL9ezleBQFxEf6C92xHTLxtGK2iLMMl47R97ntNbG9SadZu7tXCMydnxTo5OFZdAagFpGvLnfYZZBQ4fcgxWm1ZtA1VnU0sjSISs3Xz9hFkxGa0e2lJvZ96iiXMw4/WgJzff7L7+7EqmyFPXCCNfloRiweRjqTgeIHWRNzIAySk4bvk8t1/+i/cOiZBvfZKcq+eBrsVblIWzdQFwkKYEbQlwQuHI4w4B+uph/0st+ZENJTL25bblR8/FwQ=
script:
- npm run build
