language: node_js
node_js:
- stable
notifications:
  slack:
    secure: ZfWdJlfxLKiHNUYPp1aprIMUiHWVN/fCmXT4mWi8uIPW7pduITPTi68Suuyaqk/HwjAZl/YMowtlbvKhyJNnLJJu0D+n1NrsUJ4h323XnLgxmXnYsMG+a0oNX9THQU5hXxxWZXRuHN2JKhtowSdntsbTgL50oo7/87HeagC7s9QkUItNcVNl4dMU2KKJPVZOUFXiJ3LympzQRDlWeUY+YC85SoGu2lv5vvpTijtbNX+24vhUlSXBueNiJjAevlAQI8T282Hzq0hEkPWWxVCHpilF7d2x4+Dp3wqPAVS4bHrwsxS2Ahp8PTBQWdGwo2+mvJe7cQf+fWMlUFMdRsX1YJ8BHb+GdMQGQNuIYbxKxIY+Dxvv2tUtbC3FV1z6ZvSNQJ01FofiY5gkJyFRcGRZreVRb26+iKfGXKefcnwuplF/tO+er4mwLEQHshtgZCGy8HmHLXA+F+swyfhxdHHA4ZKXFRGC8xHhzdQKHGVYPEL6J4rdK7H1isifXJJway5V/cc01wr0tcejbmpZ1190MyXreD8RQmwIe9+ki0ZepocyYMddQOyJ8qB8RNrs2LWrqo71t30XC3G2oF3aSzWRJl60XI0dS+99fEABoNOUWHoNJFZGhdfRQtkW6iIt+xPIE1F8cHJK9WcJIGzClCx5Qwuzop088dxR5N7CNyI+X9Q=
script:
- npm run build
